// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Booking = { id: string, room_id: string, title: string, created_by: string, start_at: bigint, end_at: bigint, };
