// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Room = { id: string, name: string, organization_id: string, creator_id: string, };
