// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationRole } from "../enums/OrganizationRole.d";

export type CreateOrganizationMemberInput = { organization_id: string, role: OrganizationRole, };
